### ISSUE TITLE
The KITTI 2015 Pretrained Model tar file appears to be corrupt

### ISSUE THREAD

**Issue by PINTO0309** [JiaRenChang/RealtimeStereo#11]
Thanks for sharing this very nice model! :smile: 
KITTI 2015 Pretrained Model The tar file downloaded from Google Drive seems to be corrupted. The URL of the file itself seems to be fine, but the uploaded file appears to be corrupted.

- README
https://github.com/JiaRenChang/RealtimeStereo#pretrained-model

- URL
https://drive.google.com/file/d/12EQKjntE_Vi6m9vpSzJRtuzDCRJRmYoV/view?usp=sharing

- Downloaded file
pretrained_Kitti2015_realtime.tar

- Extract Error
The contents of the compressed file seem to be empty.
![Screenshot 2021-10-10 02:28:11](https://user-images.githubusercontent.com/33194443/136668481-20cf9085-8000-47f9-b49e-2ad16cb78fa4.png)

**Comment by PINTO0309** [comment]
I was mistaken. I'm very sorry.

**Comment by michaelnguyen11** [comment]
Hi,

I can't extract the pretrained_Kitti2015_realtime.tar file in Ubuntu 18.04 ? How could you do that, could you share with me ?

Thanks in advance.

**Comment by PINTO0309** [comment]
Just load the downloaded tar file into your model. There is no point in defrosting.

By the way, I've already converted it to a non-PyTorch format by applying workarounds.

- RealtimeStereo
  - TensorFlowLite, ONNX, TFJS, TF-TRT, OpenVINO, Myriad Inference Engine Blob
https://github.com/PINTO0309/PINTO_model_zoo/tree/main/165_RealtimeStereo

**Comment by danielmimimi** [comment]
Hey @PINTO0309,
thanks for your Work, I m trying to reproduce the pytorch - onnx conversion that you did : 

```
onnx_file = f"rtstereonet_maxdisp{maxdisp}_{H}x{W}.onnx"
onnx_file = model_path.parent.joinpath(onnx_file)
torch.onnx.export(
    model,
    args=(x,x),
    f=onnx_file,
    opset_version=11
)

model = onnx.load(onnx_file)
model_simp, check = simplify(model)
onnx.save(model_simp, onnx_file)
```

With your already converted ONNX model I could to this 
step "mo --input_model rtstereonet_maxdisp192_180x320.onnx --data_type FP32 --output_dir rtstereonet_maxdisp192_180x320/openvino/FR32". 

But if I finetune my RTStereonet and apply those ["steps "](https://zenn.dev/pinto0309/scraps/2766a953754dea) to avoid using the grid sample. I was not able to 1. finetune it (disparityregression2 error) 2. Just convert the Model to ONNX (simplify did throw an error), which version of from onnxsim import simplify did you use?

**Comment by PINTO0309** [comment]
You should not refer too much to a very old article from about a year ago.

Now just export with `opset=16`.

**Comment by danielmimimi** [comment]
Hey @PINTO0309, thanks for the fast reply. The pytorch version from that Repo is v 1.6, it has only opsets<=11.  This is why thought I could go the old ways. Do you have another suggestion? Directly use openvino2tensorflow to convert this network directly?
