### ISSUE TITLE
changing max_disp during inference

### ISSUE THREAD

**Issue by kaleab-k** [JiaRenChang/RealtimeStereo#16]
Hi @JiaRenChang, 
Thanks for the great work! 

I was wondering why changing the `maxdisp` during inference doesn't change the running time and result?

Thanks!

**Comment by kaleab-k** [comment]
Why is `maxdisp` manually set to 12 here: https://github.com/JiaRenChang/RealtimeStereo/blob/67d622785c8560a66a4917db0b3bb7ddfd7e127b/models/RT_stereo.py#L224

**Comment by JiaRenChang** [comment]
Hi, @kaleab-k 
Sorry for that I don't notice the manual set number.
The number 12 is from that we set maximum disparity to 192 for the original image pair; however, the matching is at 16x downsampled feature maps.
The disparity at 16x downsampled feature maps is 192/16 = 12.

**Comment by kaleab-k** [comment]
Understood. Thank you, @JiaRenChang!
