### ISSUE TITLE
TensorRT

### ISSUE THREAD

**Issue by kaleab-k** [JiaRenChang/RealtimeStereo#18]
Hi @JiaRenChang, 

I was wondering if you tried TensorRT and observed an inference speed improvement?

Thanks!

**Comment by Genlk** [comment]
hello,have you ever download the unbroken pretrained model file?
Could you please send the file to me

**Comment by kaleab-k** [comment]
Hi @Genlk, what do you mean by unbroken? I am using [this file ](https://drive.google.com/file/d/12EQKjntE_Vi6m9vpSzJRtuzDCRJRmYoV/view?usp=sharing)
