### ISSUE TITLE
The pretrained model  file seems to be broken.Does any one who has a good one ?

### ISSUE THREAD

**Issue by Genlk** [JiaRenChang/RealtimeStereo#19]

**Comment by Genlk** [comment]
change a vpn,I have get the unbroken file

**Comment by philleer** [comment]
same problem, the downloaded tar ball can not be extracted @JiaRenChang

**Comment by DWJ111** [comment]
May I ask if your pre trained model is still available? The model size I downloaded is only 131 KB. Thank you. @Genlk @JiaRenChang

**Comment by 2c984r83y** [comment]
> May I ask if your pre trained model is still available? The model size I downloaded is only 131 KB. Thank you. @Genlk @JiaRenChang

The pre-trained model I downloaded is also 131KB, but I am  unable to run Test_img.py, same as  https://github.com/JiaRenChang/RealtimeStereo/issues/17#issue-1330724237. 
I notice that the model argument is `RTStereoNet`, not `stackhourglass`, you need to chage default argument in `Test_img.py`
```python
#parser.add_argument('--model', default='stackhourglass', help='select model')
parser.add_argument('--model', default='RTStereoNet',  help='select model')
```

**Comment by flyxuexi** [comment]
> > May I ask if your pre trained model is still available? The model size I downloaded is only 131 KB. Thank you. @Genlk @JiaRenChang
> 
> The pre-trained model I downloaded is also 131KB, but I am unable to run Test_img.py, same as [#17 (comment)](https://github.com/JiaRenChang/RealtimeStereo/issues/17#issue-1330724237). I notice that the model argument is `RTStereoNet`, not `stackhourglass`, so just follow `run.sh`
> 
> ```shell
> #!/bin/bash
> 
> python main.py --maxdisp 192 \
>                --model stackhourglass \
>                --datapath dataset/ \
>                --epochs 0 \
>                --loadmodel ./trained/checkpoint_10.tar \
>                --savemodel ./trained/
> 
> 
> 
> python finetune.py --maxdisp 192 \
>                    --model stackhourglass \
>                    --datatype 2015 \
>                    --datapath dataset/data_scene_flow_2015/training/ \
>                    --epochs 300 \
>                    --loadmodel ./trained/checkpoint_10.tar \
>                    --savemodel ./trained/
> ```
> 
> or chage default argument in `Test_img.py`
> 
> ```python
> #parser.add_argument('--model', default='stackhourglass', help='select model')
> parser.add_argument('--model', default='RTStereoNet',  help='select model')
> ```

同学你好，能请教一个问题吗。在Test_img.py中，我将stackhourglass改为了RTStereoNet，但下面的内容出现了报错：
parser.add_argument('--leftimg', default= './VO04_L.png',
                    help='load model')
parser.add_argument('--rightimg', default= './VO04_R.png',
                    help='load model')              
这里需要的是什么左右图呀，没有头绪
另外注意到我们的研究方向有些相似，能加个联系方式吗，我是dlut的研究生
感谢

**Comment by flyxuexi** [comment]
> ```shell
> stackhourglass
> ```

我感觉将main.py和finetune.py的model改成stackhourglass不太合适。
因为作者相同的缘故，代码中的stackhourglass和basic是从PSMNet项目移过来的，只有RTStereoNet是本项目新提出的

**Comment by flyxuexi** [comment]
> > May I ask if your pre trained model is still available? The model size I downloaded is only 131 KB. Thank you. @Genlk @JiaRenChang
> 
> The pre-trained model I downloaded is also 131KB, but I am unable to run Test_img.py, same as [#17 (comment)](https://github.com/JiaRenChang/RealtimeStereo/issues/17#issue-1330724237). I notice that the model argument is `RTStereoNet`, not `stackhourglass`, so just follow `run.sh`
> 
> ```shell
> #!/bin/bash
> 
> python main.py --maxdisp 192 \
>                --model stackhourglass \
>                --datapath dataset/ \
>                --epochs 0 \
>                --loadmodel ./trained/checkpoint_10.tar \
>                --savemodel ./trained/
> 
> 
> 
> python finetune.py --maxdisp 192 \
>                    --model stackhourglass \
>                    --datatype 2015 \
>                    --datapath dataset/data_scene_flow_2015/training/ \
>                    --epochs 300 \
>                    --loadmodel ./trained/checkpoint_10.tar \
>                    --savemodel ./trained/
> ```
> 
> or chage default argument in `Test_img.py`
> 
> ```python
> #parser.add_argument('--model', default='stackhourglass', help='select model')
> parser.add_argument('--model', default='RTStereoNet',  help='select model')
> ```

我感觉将main.py和finetune.py的model改成stackhourglass不太合适。
因为作者相同的缘故，代码中的stackhourglass和basic是从PSMNet项目移过来的，只有RTStereoNet是本项目新提出的

**Comment by 2c984r83y** [comment]
> > > May I ask if your pre trained model is still available? The model size I downloaded is only 131 KB. Thank you. @Genlk @JiaRenChang
> > 
> > 
> > The pre-trained model I downloaded is also 131KB, but I am unable to run Test_img.py, same as [#17 (comment)](https://github.com/JiaRenChang/RealtimeStereo/issues/17#issue-1330724237). I notice that the model argument is `RTStereoNet`, not `stackhourglass`, so just follow `run.sh`
> > ```shell
> > #!/bin/bash
> > 
> > python main.py --maxdisp 192 \
> >                --model stackhourglass \
> >                --datapath dataset/ \
> >                --epochs 0 \
> >                --loadmodel ./trained/checkpoint_10.tar \
> >                --savemodel ./trained/
> > 
> > 
> > 
> > python finetune.py --maxdisp 192 \
> >                    --model stackhourglass \
> >                    --datatype 2015 \
> >                    --datapath dataset/data_scene_flow_2015/training/ \
> >                    --epochs 300 \
> >                    --loadmodel ./trained/checkpoint_10.tar \
> >                    --savemodel ./trained/
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > or chage default argument in `Test_img.py`
> > ```python
> > #parser.add_argument('--model', default='stackhourglass', help='select model')
> > parser.add_argument('--model', default='RTStereoNet',  help='select model')
> > ```
> 
> 我感觉将main.py和finetune.py的model改成stackhourglass不太合适。 因为作者相同的缘故，代码中的stackhourglass和basic是从PSMNet项目移过来的，只有RTStereoNet是本项目新提出的

没错，你是对的。我之前的回复写错了，我当时没意识到`run.sh`中的参数是`stackhourglass`, 这不对，应当改为`RTStereoNet`. 但是后面把参数改为`RTStereoNet`这段是没问题的。
```python
#parser.add_argument('--model', default='stackhourglass', help='select model')
parser.add_argument('--model', default='RTStereoNet',  help='select model')
```
所以我修改了之前的回复，去掉了有关`run.sh`的内容，保留了将模型修改为`RTStereoNet`的内容。
左右图就是双目相机采集到的一对图像，你报错可能是因为图像的文件路径不对？你可以换成绝对路径试一下。
这是我的电子邮箱: zhao32450039@gmail.com，请多多指教！

**Comment by flyxuexi** [comment]
> > > > May I ask if your pre trained model is still available? The model size I downloaded is only 131 KB. Thank you. @Genlk @JiaRenChang
> > > 
> > > 
> > > The pre-trained model I downloaded is also 131KB, but I am unable to run Test_img.py, same as [#17 (comment)](https://github.com/JiaRenChang/RealtimeStereo/issues/17#issue-1330724237). I notice that the model argument is `RTStereoNet`, not `stackhourglass`, so just follow `run.sh`
> > > ```shell
> > > #!/bin/bash
> > > 
> > > python main.py --maxdisp 192 \
> > >                --model stackhourglass \
> > >                --datapath dataset/ \
> > >                --epochs 0 \
> > >                --loadmodel ./trained/checkpoint_10.tar \
> > >                --savemodel ./trained/
> > > 
> > > 
> > > 
> > > python finetune.py --maxdisp 192 \
> > >                    --model stackhourglass \
> > >                    --datatype 2015 \
> > >                    --datapath dataset/data_scene_flow_2015/training/ \
> > >                    --epochs 300 \
> > >                    --loadmodel ./trained/checkpoint_10.tar \
> > >                    --savemodel ./trained/
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > or chage default argument in `Test_img.py`
> > > ```python
> > > #parser.add_argument('--model', default='stackhourglass', help='select model')
> > > parser.add_argument('--model', default='RTStereoNet',  help='select model')
> > > ```
> > 
> > 
> > 我感觉将main.py和finetune.py的model改成stackhourglass不太合适。 因为作者相同的缘故，代码中的stackhourglass和basic是从PSMNet项目移过来的，只有RTStereoNet是本项目新提出的
> 
> 没错，你是对的。我之前的回复写错了，我当时没意识到`run.sh`中的参数是`stackhourglass`, 这不对，应当改为`RTStereoNet`. 但是后面把参数改为`RTStereoNet`这段是没问题的。
> 
> ```python
> #parser.add_argument('--model', default='stackhourglass', help='select model')
> parser.add_argument('--model', default='RTStereoNet',  help='select model')
> ```
> 
> 所以我修改了之前的回复，去掉了有关`run.sh`的内容，保留了将模型修改为`RTStereoNet`的内容。 左右图就是双目相机采集到的一对图像，你报错可能是因为图像的文件路径不对？你可以换成绝对路径试一下。 这是我的电子邮箱: [zhao32450039@gmail.com](mailto:zhao32450039@gmail.com)，请多多指教！

谢谢，刚解决就看到回复了,结果确实挺模糊的hh，希望有机会多交流～我的wx发邮箱了
