### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by Abhishekvats1997** [JiaRenChang/RealtimeStereo#3]
First of all thank you for open sourcing your work. Do you plan to release pre-trained models ?

**Comment by JiaRenChang** [comment]
@Abhishekvats1997 
Because the model is very small, training this model on a single high performance GPU (such as 1060Ti) is very quick, usually takes hours.
We do not attempt to release pre-trained model now; however, if you can not train model by yourself, we still can provide it.

**Comment by Abhishekvats1997** [comment]
@JiaRenChang I currently do not have access to a high perf GPU but have a Jetson Xavier at my disposal for inference. If you could provide a pre-trained model that would be a great help for my use case.

**Comment by JiaRenChang** [comment]
@Abhishekvats1997 

We add a link to google drive in README  for downloading a pretrained model on KITTI2015

**Comment by Abhishekvats1997** [comment]
@JiaRenChang Thank You so much.

**Comment by Abhishekvats1997** [comment]
@JiaRenChang state dict of the weights provided does not seem to match the model architecture.

**Comment by JiaRenChang** [comment]
@Abhishekvats1997 
You use Test_img.py?
You can comment line 51 "model = nn.DataParallel(model, device_ids=[0])" in Test_img.py.

**Comment by LeeyqSenSe** [comment]
It seems the model you provided is stackhourglass, but not RTStereo, which means it can not run fast on edge deivce, is that True？

**Comment by TITAINc** [comment]
@JiaRenChang The downloaded pre training model data is damaged. Can you upload a copy again?

**Comment by JiaRenChang** [comment]
@TITAINc 
Hi, I test the google drive link  and it works.
Would you try again?
