### ISSUE TITLE
Why many files are *.pyc ?

### ISSUE THREAD

**Issue by Hahaemmm** [JiaRenChang/RealtimeStereo#4]
Many codes are .pyc files instead of .py files. Is the file missing?

**Comment by JiaRenChang** [comment]
@Hahaemmm 
   No file missed.  The .pyc files are byte-complied files by python.

**Comment by Hahaemmm** [comment]
> @Hahaemmm
> No file missed. The .pyc files are byte-complied files by python.

So you will not release code that contains .py files?

**Comment by Abhishekvats1997** [comment]
@Hahaemmm Yes the files are missing. What you can do is copy the corresponding .py files for each .pyc file from the PSMNet repo. This is what I did when trying to train the model.

**Comment by Abhishekvats1997** [comment]
@JiaRenChang when running the main.py for training it imports files which are not there such as SenceFlowLoader. I copied them from the PSMNet repo should i not do this ?

**Comment by Hahaemmm** [comment]
copy the corresponding .py files for each .pyc file from the PSMNet repo

OK ..thanks a lot
